// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: dictionary.proto

/*
Package service is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package service

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_EnglishDictionaryService_EnglishDictionarySearchWord_0(ctx context.Context, marshaler runtime.Marshaler, client EnglishDictionaryServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq EnglishDictionarySearchWordRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["word"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "word")
	}

	protoReq.Word, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "word", err)
	}

	msg, err := client.EnglishDictionarySearchWord(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_EnglishDictionaryService_EnglishDictionarySearchWord_0(ctx context.Context, marshaler runtime.Marshaler, server EnglishDictionaryServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq EnglishDictionarySearchWordRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["word"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "word")
	}

	protoReq.Word, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "word", err)
	}

	msg, err := server.EnglishDictionarySearchWord(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterEnglishDictionaryServiceHandlerServer registers the http handlers for service EnglishDictionaryService to "mux".
// UnaryRPC     :call EnglishDictionaryServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterEnglishDictionaryServiceHandlerFromEndpoint instead.
func RegisterEnglishDictionaryServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server EnglishDictionaryServiceServer) error {

	mux.Handle("GET", pattern_EnglishDictionaryService_EnglishDictionarySearchWord_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/pb.EnglishDictionaryService/EnglishDictionarySearchWord", runtime.WithHTTPPathPattern("/v1/englishDictionarySearchWord/{word}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_EnglishDictionaryService_EnglishDictionarySearchWord_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EnglishDictionaryService_EnglishDictionarySearchWord_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterEnglishDictionaryServiceHandlerFromEndpoint is same as RegisterEnglishDictionaryServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterEnglishDictionaryServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterEnglishDictionaryServiceHandler(ctx, mux, conn)
}

// RegisterEnglishDictionaryServiceHandler registers the http handlers for service EnglishDictionaryService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterEnglishDictionaryServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterEnglishDictionaryServiceHandlerClient(ctx, mux, NewEnglishDictionaryServiceClient(conn))
}

// RegisterEnglishDictionaryServiceHandlerClient registers the http handlers for service EnglishDictionaryService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "EnglishDictionaryServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "EnglishDictionaryServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "EnglishDictionaryServiceClient" to call the correct interceptors.
func RegisterEnglishDictionaryServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client EnglishDictionaryServiceClient) error {

	mux.Handle("GET", pattern_EnglishDictionaryService_EnglishDictionarySearchWord_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/pb.EnglishDictionaryService/EnglishDictionarySearchWord", runtime.WithHTTPPathPattern("/v1/englishDictionarySearchWord/{word}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_EnglishDictionaryService_EnglishDictionarySearchWord_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EnglishDictionaryService_EnglishDictionarySearchWord_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_EnglishDictionaryService_EnglishDictionarySearchWord_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "englishDictionarySearchWord", "word"}, ""))
)

var (
	forward_EnglishDictionaryService_EnglishDictionarySearchWord_0 = runtime.ForwardResponseMessage
)
